CREATE OR ALTER PROCEDURE INSERTION_BOOKING
(
	@BOOKING_ID INT,
	@STATUS VARCHAR(50),
	@TOTAL_PRICE FLOAT,
	@ECHECKIN_DATE DATETIME,
	@ECHECKOUT_DATE DATETIME,
	@USER_ID INT,
	@HOTEL_ID INT,
	@ROOM_ID INT,
	@PAYMENT_ID INT
)
AS 
INSERT INTO Booking.Booking
VALUES 
(
	@BOOKING_ID,
	@STATUS,
	@TOTAL_PRICE,
	@ECHECKIN_DATE,
	@ECHECKOUT_DATE,
	@USER_ID,
	@HOTEL_ID,
	@ROOM_ID,
	@PAYMENT_ID
)


EXEC INSERTION_BOOKING
@BOOKING_ID = 1,
@STATUS = 'Confirmed',
@TOTAL_PRICE = 5000,
@ECHECKIN_DATE = '2024-05-4 00:00:00',
@ECHECKOUT_DATE = '2024-05-20 00:00:00',
@USER_ID = 1,
@HOTEL_ID = 1,
@ROOM_ID = 11,
@PAYMENT_ID = 1


EXEC INSERTION_BOOKING
@BOOKING_ID = 2,
@STATUS = 'Confirmed',
@TOTAL_PRICE = 3000,
@ECHECKIN_DATE = '2024-05-4 00:00:00',
@ECHECKOUT_DATE = '2024-05-25 00:00:00',
@USER_ID = 2,
@HOTEL_ID = 1,
@ROOM_ID = 12,
@PAYMENT_ID = 2

select * from Booking.Payment


EXEC INSERTION_BOOKING
@BOOKING_ID = 3,
@STATUS = 'Confirmed',
@TOTAL_PRICE = 3580,
@ECHECKIN_DATE = '2024-06-10 00:00:00',
@ECHECKOUT_DATE = '2024-06-20 00:00:00',
@USER_ID = 3,
@HOTEL_ID = 2,
@ROOM_ID = 21,
@PAYMENT_ID = 1


EXEC INSERTION_BOOKING
@BOOKING_ID = 4,
@STATUS = 'Canceled',
@TOTAL_PRICE = 3500,
@ECHECKIN_DATE = '2024-06-10 00:00:00',
@ECHECKOUT_DATE = null,
@USER_ID = 4,
@HOTEL_ID = 2,
@ROOM_ID = 22,
@PAYMENT_ID = 3


EXEC INSERTION_BOOKING
@BOOKING_ID = 5,
@STATUS = 'Confirmed',
@TOTAL_PRICE = 3600,
@ECHECKIN_DATE = '2024-06-10 00:00:00',
@ECHECKOUT_DATE = '2024-07-01 00:00:00',
@USER_ID = 4,
@HOTEL_ID = 1,
@ROOM_ID = 13,
@PAYMENT_ID = 1


----------------------------------------------------------------------------------------------------------------------- UPDATE


CREATE OR ALTER PROCEDURE UPDATE_BOOKING
(@BOOKING_ID INT, @STATUS VARCHAR(50), @TOTAL_PRICE FLOAT, @ECHECKIN_DATE DATETIME, @ECHECKOUT_DATE DATETIME, @USER_ID INT, @HOTEL_ID INT, @ROOM_ID INT, @PAYMENT_ID INT)
AS 
UPDATE Booking.Booking
SET Booking_Id= @BOOKING_ID, Status=@STATUS,Total_Price=@TOTAL_PRICE,CheckIn_Date=@ECHECKIN_DATE,CheckOut_Date=@ECHECKOUT_DATE,User_Id=@USER_ID,Hotel_Id=@HOTEL_ID,Room_Id=@ROOM_ID,Payment_Id=@PAYMENT_ID where Booking_Id= @BOOKING_ID

----------------------------------------------------------------------------------------------------------------------- DELETE

CREATE OR ALTER PROCEDURE DELETE_BOOKING (@BOOKING_ID INT)
AS 
DELETE Booking.Booking
where Booking_Id= @BOOKING_ID
